platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
- name: decoders

run:
  path: sh
  before_script: - chmod +x gradlew
  args: ["decoders/ci/tasks/build.sh"]
